repos:
  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: v1.9.0
    hooks:
      - id: poetry-export
        entry: poetry export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
        files: ^pyproject\.toml$
