repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '2.0.*'
    hooks:
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
        files: ^pyproject\.toml$
