[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dbxmetagen"
version = "0.2.3"
description = "Generates comments and other metadata for Delta tables in Databricks."
readme = "README.md"
requires-python = ">=3.11"
license = "Apache-2.0"
dependencies = [
  'numpy >= 1.21.1',
  'databricks-sdk>=0.20',
  'mlflow==2.18.0',
  'databricks_vectorsearch>=0.23',
  'overrides>=7.7.0',
  'nest-asyncio>=1.5.6',
  'pkginfo>=1.10.0',
  'openai==1.56.1',
  'cloudpickle==3.1.0',
  'transformers==4.46.3',
  'torchvision==0.20.1',
  'torch==2.5.1',
  'pydantic==2.9.2'
  ]
