command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: DEBUG
    value: "true"
  # DATABRICKS_HOST is automatically provided by Databricks Apps
  # Service principal authentication is handled automatically
  - name: APP_ENV
    value: "dev"  # use "prod" in production deployments
  - name: DEPLOY_USER_NAME
    value: ""  # optional: set to the deploying user's email (e.g., user@company.com)
  - name: NOTEBOOK_PATH
    value: "/Workspace/Users/eli.swanson@databricks.com/.bundle/dbxmetagen/dev/files/notebooks/generate_metadata"  # Use bundle user path
