# DBX MetaGen App Configuration
app:
  title: "DBX MetaGen"
  description: "AI-Powered Metadata Generation, Identification, and Classification for Databricks"
  version: "1.0.0"
  
# Default job configuration  
job_defaults:
  spark_version: "16.4.x-cpu-ml-scala2.12"
  node_type_id: "Standard_D3_v2"  # Update based on your cloud provider
  notebook_path: "./notebooks/generate_metadata"
  
# Cluster size mappings
cluster_sizes:
  small:
    min_workers: 1
    max_workers: 2
    display_name: "Small (1-2 workers)"
  medium:
    min_workers: 2
    max_workers: 4
    display_name: "Medium (2-4 workers)"
  large:
    min_workers: 4
    max_workers: 8
    display_name: "Large (4-8 workers)"

# Available models
models:
  - "databricks-claude-3-7-sonnet"
  - "databricks-meta-llama-3-3-70b-instruct"

# Processing modes
modes:
  - "comment"
  - "pi"